DROP TABLE IF EXISTS data_tp1;

CREATE TABLE data_tp1 (id INTEGER PRIMARY KEY AUTOINCREMENT, author TEXT NOT NULL, created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, weight_id INTEGER NOT NULL, height_id INTEGER NOT NULL, imc_id INTEGER NOT NULL);