DROP TABLE IF EXISTS data_tp1;
CREATE TABLE data_tp1 (id INTEGER NOT NULL AUTO_INCREMENT, author TEXT NOT NULL, created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, weight_id FLOAT NOT NULL, height_id FLOAT NOT NULL, imc_id FLOAT NOT NULL, PRIMARY KEY (id));
